.TH GF_ATTACH: "8" "July 2017"
.SH NAME
gf_attach: \- attach and detach volumes
.SH SYNOPSIS
.B gf_attach
\fI\,uds_path volfile_path (to attach)\/\fR
.SH USAGE
.IP
gf_attach uds_path volfile_path (to attach)
.IP
gf_attach \fB\-d\fR uds_path brick_path (to detach)
.SH "AUTHOR"
This manual page was written by Patrick Matth\[:a]i <pmatthaei@debian.org>
for glusterfs.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, Version 2 any
later version published by the Free Software Foundation.
